name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: node-app-ci-cd
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  AWS_ACCOUNT_ID: 808850079759

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #################################
      # INSTALL NODE + DEPENDENCIES
      #################################

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      #################################
      # SNYK DEPENDENCY SCAN
      #################################

      - name: Run Snyk Dependency Scan
        uses: snyk/actions/node@master
        with:
          command: test
          args: --severity-threshold=high
          working-directory: ./app
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      #################################
      # AWS AUTH
      #################################

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      #################################
      # BUILD IMAGE
      #################################

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      #################################
      # SNYK CONTAINER SCAN
      #################################

      - name: Run Snyk Container Scan
        uses: snyk/actions/docker@master
        with:
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      #################################
      # PUSH IMAGE
      #################################

      - name: Push Docker image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      #################################
      # DEPLOY TO EKS
      #################################

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Update image in deployment.yaml
        run: |
          sed -i "s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}|" k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/